"""Run every aml-practice/*.py, capture stdout, and write aml-exam-prep/data/code_bundle.js (window.CODE).
The site shows exactly this code and this output, so the page always matches the real program."""
import json, os, subprocess, sys, glob
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PRACTICE = os.path.join(ROOT, "aml-practice")
OUT = os.path.join(ROOT, "aml-exam-prep", "data", "code_bundle.js")
PY = sys.executable
bundle, failed = {}, []
for path in sorted(glob.glob(os.path.join(PRACTICE, "*.py"))):
    name = os.path.basename(path)
    r = subprocess.run([PY, "-W", "ignore", path], capture_output=True, text=True, cwd=PRACTICE, timeout=300)
    if r.returncode != 0:
        failed.append(name); print("FAILED:", name, r.stderr[-400:])
    code = open(path, encoding="utf-8").read()
    bundle[name] = {"code": code.rstrip("\n"), "output": r.stdout.rstrip("\n")}
with open(OUT, "w", encoding="utf-8") as f:
    f.write("/* GENERATED by tools/build_code.py — do not edit by hand. */\nwindow.CODE = ")
    json.dump(bundle, f, ensure_ascii=False, indent=0)
    f.write(";\n")
print(f"bundled {len(bundle)} programs, {len(failed)} failed")
sys.exit(1 if failed else 0)
